### ISSUE TITLE
Add SDRPlay Rsp1

### ISSUE THREAD

**Issue by F5OEO** [f4exb/sdrdaemon#13]
Any chance to add these devices ?

**Comment by f4exb** [comment]
LimeSDR already covered by #9 
These two have rich features so it can be considered as relatively complex

**Comment by f4exb** [comment]
Superseded by https://github.com/f4exb/sdrangel/issues/196
SDRdaemon is going EOL

**Comment by f4exb** [comment]
Delivered in SDRangel v4.1.0
