### ISSUE TITLE
Network traffic seems *2 

### ISSUE THREAD

**Issue by F5OEO** [f4exb/sdrdaemon#14]
SdrDaemon works on arm64 (Rock64), RTL-SOURCE.
Network traffic seems not coherent depending on samplerate : 
Example : SR = 1400 / Decim = 1 should make a traffic of 1400*2bytes/s : 2.8Mbyte/s .
We have 5.6Mbytes instead
![sdrdaemon](https://user-images.githubusercontent.com/6190918/30798888-643800b6-a1db-11e7-96f1-c0eaa3b38013.png)

**Comment by f4exb** [comment]
Hello my friend!
I think we discussed it in PM: the reason is that samples are on 4 bytes not 2. These are I/Q samples on 16 bits therefore 16*2 = 32 bits = 4 bytes.
