### ISSUE TITLE
SDRdaemonSourceUDPHandler::start: cannot bind data port 9092

### ISSUE THREAD

**Issue by jrsphoto** [f4exb/sdrdaemon#15]
I have been trying to test the SDRdaemonSource between two computers, an i5 in my lab running sdrdaemonrd (192.168.11.85) with an RTL-SDR, and my laptop running SDRAngel, (192.168.11.86), but i have been getting the following error.

`SDRdaemonSourceUDPHandler::start: cannot bind data port 9092`

 No connection is made to the remote sdrdaemonrx instance.  

On the lab computer with the RTL-SDR, I run this command:
`sdrdaemonrx -t rtlsdr -I 192.168.10.36 -D 9092 -C 9093 -c txdelay=300,fecblk=8,freq=433970000,srate=1000000,ppmp=58,gain=40.2,decim=5,fcpos=2`

From my laptop (192.168.11.86 I launch sdrangel from the terminal and select SDRdaemonSource as the sampling source. I enter the IP address of the i5 the data port, and the control port, click set, and immediately get the above error in the terminal where I launched sdrangel.

I have tried about 20 different values for the UDP data port, nothing works, and the error I get reflects the port number I'm using in every case.  

The computers are connected via Ethernet on the same gigabit switch.  Also, sdrdmnctl is able to control the remote sdrdaemonrx instance without an issue.

If I can give you any other info, let me know (jrsphoto@gmail.com)

-John

**Comment by f4exb** [comment]
Hello,
the reason is that you have to enter the address of the laptop not the i5. You are in fact telling the program on the laptop on which interface it should receive the samples. I don't  know if this is made very clear in the SDRangel documentation (I have to check that)  but the tooltip says "Local data connection IP address"
Best regards.
