### ISSUE TITLE
Support for PlutoSDR

### ISSUE THREAD

**Issue by unixpunk** [f4exb/sdrdaemon#16]
Since the PlutoSDR actually has an ARMv7 dual core (manually have to enable second core) and already runs Linux, it should be very possible for sdrdaemon to run ON the device itself already.  (I will confirm this and reply to this thread.)  Since it also supports OTG networking and WiFi, the PlutoSDR with sdrdaemon could be a stand-alone remote rx/tx device, even powered by a battery instead of having to be plugged into a computer.  Needless to say, this would be cool to have.  :)  Thanks for considering!

**Comment by unixpunk** [comment]
After thinking further, I wonder if its not powerful enough to send all that IQ data without dropping packets like I see when running on a Pi3.  If that is the case, then this would just be a normal device support request and not as cool as a standalone unit.  (Building the PlutoSDR fw from source allows on to add in almost any dep needed, such as nanomsg.)  The building of sdrdaemon/cm256cc would then be done on a PC cross-compiling using the Xilinx SDK and uploaded to the Pluto for execution.  Once known-working, it could then be overlayed on to the rootfs during the build process.

**Comment by unixpunk** [comment]
In case its useful, here's a port of dump1090 that was switched from rtlsdr support to PlutSDR support, though I would guess there's sdrangel code that would be adaptable here as well, obviously you'd know best!  https://github.com/PlutoSDR/dump1090/commit/7be97a405b5fe6651f50bc9a293c87d52505a3e2

**Comment by f4exb** [comment]
Superseded by https://github.com/f4exb/sdrangel/issues/196
SDRdaemon is going EOL

**Comment by f4exb** [comment]
Delivered in SDRangel v4.1.0
