### ISSUE TITLE
Decoding data

### ISSUE THREAD

**Issue by dgorissen** [f4exb/sdrdaemon#3]
Im trying to write a simple python client to decode the data stream. Using an airspy, no FEC, no compression.

My understanding is the first 42 bytes should contain the meta frame which I am reading/decoding with the python struct module [as described here](https://docs.python.org/2/library/struct.html#struct-alignment).

I started off with something very simple.

```
import select, socket
from struct import *

port = 19090
bufferSize = 512

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(('localhost', port))
s.setblocking(0)

i=0
while i<10:
        result = select.select([s],[],[])
        msg = result[0][0].recv(bufferSize)
        msg = msg[:42]
        #print ' '.join('{0:08b}'.format(ord(x), 'b') for x in msg) # log raw bytes
        print unpack(">QIxBHIHIIIQ", msg)  # big endian
        i += 1
```

While Im receiving data, it does not decode into any numbers that make sense. So either Im missing something obvious and/or its missing synchronisation. However Im on unfamiliar territory here so a bit of guidance would be greatly appreciated.

**Comment by dgorissen** [comment]
Any pointers? Would love to use it.

**Comment by rajibeee** [comment]
@dgorissen I think you can see the actual data that is being sent by using [Packet Sender](https://packetsender.com/). The ASCII portion is the actual data. 

![1](https://cloud.githubusercontent.com/assets/23200508/21751766/6e0d5f04-d59a-11e6-9b9e-ceb4f8d83769.PNG)


But I am yet to figure out how do I get the I/Q values from these data. I do not know if they are sending the compressed or uncompressed data. Did you make any progress on this ?

**Comment by f4exb** [comment]
See the main readme [here](https://github.com/f4exb/sdrdaemon#data-formats)
