### ISSUE TITLE
Support for LimeSDR

### ISSUE THREAD

**Issue by E3V3A** [f4exb/sdrdaemon#9]
How can we provide support for `LimeSDR`?

**Comment by f4exb** [comment]
Assuming Tx side is only in dev at the moment for the Rx part it is basically creating a new derivative of the virtual Source class along these lines: "class LimeSDRSource : public DeviceSource..." Inspiration can be taken both from the corresponding Rx plugin in SDRangel and an existing class in SDRdaemon like HackRFSource.

Then adding the code to sdrdaemon and sdrdaemonfec executables. Will need also to include LimeSuite in the Debian distribution to ease deployment.

Assuming only one Rx is supported simultaneously this shouldn't be too difficult.

**Comment by f4exb** [comment]
Considering all the problems encountered with LimeSDR and SDRangel this is not going to be anytime soon.

**Comment by f4exb** [comment]
Superseded by https://github.com/f4exb/sdrangel/issues/196
SDRdaemon is going EOL

**Comment by f4exb** [comment]
Delivered in SDRangel v4.1.0
